
export const SIGN_IN_REQUEST="SIGN_IN_REQUEST"
export const SIGN_IN_SUCCESS="SIGN_IN_SUCCESS"
export const SIGN_IN_FAILED="SIGN_IN_FAILED"



export const SIGN_UP_REQUEST="SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS="SIGN_UP_SUCCESS"
export const SIGN_UP_FAILED="SIGN_UP_FAILED"



export const SIGN_OUT_REQUEST="SIGN_OUT_REQUEST"
export const SIGN_OUT_SUCCESS="SIGN_OUT_SUCCESS"
export const SIGN_OUT_FAILED="SIGN_OUT_FAILED"

export const CHANGE_PASSWORD_REQUEST="CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED"