



const FETCH_CART_REQUEST="FETCH_CART_REQUEST"
const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS"
const FETCH_CART_FAILED="FETCH_CART_FAILED"

const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
const ADD_TO_CART_FAILED="ADD_TO_CART_FAILED"

const REMOVE_FROM_CART_REQUEST=" REMOVE_FROM_CART_REQUEST"
const REMOVE_FROM_CART_SUCCESS="REMOVE_FROM_CART_SUCCESS"
const REMOVE_FROM_CART_FAILED="REMOVE_FROM_CART_FAILED"

const CHANGE_QUANTITY_REQUEST=" CHANGE_QUANTITY_REQUEST"
const CHANGE_QUANTITY_SUCCESS="CHANGE_QUANTITY_SUCCESS"
const CHANGE_QUANTITY_FAILED="CHANGE_QUANTITY_FAILED"

export
{
   FETCH_CART_FAILED,
   FETCH_CART_REQUEST,
   FETCH_CART_SUCCESS,

    ADD_TO_CART_REQUEST,
    ADD_TO_CART_SUCCESS,
    ADD_TO_CART_FAILED,

   REMOVE_FROM_CART_REQUEST,
   REMOVE_FROM_CART_SUCCESS,
   REMOVE_FROM_CART_FAILED,
   
   CHANGE_QUANTITY_REQUEST,
   CHANGE_QUANTITY_SUCCESS,
   CHANGE_QUANTITY_FAILED
}




