



const FETCH_CART_REQUEST="FETCH_CART_REQUEST"
const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS"
const FETCH_CART_FAILED="FETCH_CART_FAILED"
const ADD_TO_CART_REQUEST="ADD_TO_CART_REQUEST"
const ADD_TO_CART_SUCCESS="ADD_TO_CART_SUCCESS"
const ADD_TO_CART_FAILED="ADD_TO_CART_FAILED"
const REMOVE_FROM_CART=" REMOVE_FROM_CART"
const LOAD_CART_ITEMS="LOAD_CART_ITEMS"
const CHANGE_QUANTITY="CHANGE_QUANTITY"

export
{
   FETCH_CART_FAILED,FETCH_CART_REQUEST,FETCH_CART_SUCCESS, ADD_TO_CART_REQUEST,ADD_TO_CART_SUCCESS,ADD_TO_CART_FAILED,REMOVE_FROM_CART,LOAD_CART_ITEMS,CHANGE_QUANTITY
}




