const ADD_COMMENT_REQUEST="ADD_COMMENT_REQUEST"
const ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS"
const ADD_COMMENT_FAILED="ADD_COMMENT_FAILED"

const LOAD_COMMENTS_REQUEST="LOAD_COMMENTS_REQUEST"
const LOAD_COMMENTS_SUCCESS="LOAD_COMMENTS_SUCCESS"
const LOAD_COMMENTS_FAILED="LOAD_COMMENTS_FAILED"

const LOAD_MORE_COMMENTS_REQUEST="LOAD_MORE_COMMENTS_REQUEST"
const LOAD_MORE_COMMENTS_SUCCESS="LOAD_MORE_COMMENTS_SUCCESS"
const LOAD_MORE_COMMENTS_FAILED="LOAD_MORE_COMMENTS_FAILED"

const LOAD_EXTERNAL_DETAILS_REQUEST="LOAD_EXTERNAL_DETAILS_REQUEST"
const LOAD_EXTERNAL_DETAILS_SUCCESS="LOAD_EXTERNAL_DETAILS_SUCCESS"
const LOAD_EXTERNAL_DETAILS_FAILED="LOAD_EXTERNAL_DETAILS_FAILED"



export
{
    ADD_COMMENT_FAILED,
    ADD_COMMENT_REQUEST,
    ADD_COMMENT_SUCCESS,

    LOAD_EXTERNAL_DETAILS_REQUEST,
    LOAD_EXTERNAL_DETAILS_SUCCESS,
    LOAD_EXTERNAL_DETAILS_FAILED,

    LOAD_COMMENTS_REQUEST,
    LOAD_COMMENTS_SUCCESS,
    LOAD_COMMENTS_FAILED,

    LOAD_MORE_COMMENTS_REQUEST,
    LOAD_MORE_COMMENTS_SUCCESS,
    LOAD_MORE_COMMENTS_FAILED,

}