const ADD_FEATURED_REQUEST="ADD_FEATURED_REQUEST"
const ADD_FEATURED_SUCCESS="ADD_FEATURED_SUCCESS"
const ADD_FEATURED_FAILED="ADD_FEATURED_FAILED"


const DELETE_FEATURED_REQUEST="DELETE_FEATURED_REQUEST"
const DELETE_FEATURED_SUCCESS="DELETE_FEATURED_SUCCESS"
const DELETE_FEATURED_FAILED="DELETE_FEATURED_FAILED"


const LOAD_FEATURED_REQUEST="LOAD_FEATURED_REQUEST"
const LOAD_FEATURED_SUCCESS="LOAD_FEATURED_SUCCESS"
const LOAD_FEATURED_FAILED="LOAD_FEATURED_FAILED"


export
{
    ADD_FEATURED_REQUEST,
    ADD_FEATURED_SUCCESS,
    ADD_FEATURED_FAILED,


    DELETE_FEATURED_REQUEST,
    DELETE_FEATURED_SUCCESS,
    DELETE_FEATURED_FAILED,


    LOAD_FEATURED_REQUEST,
    LOAD_FEATURED_SUCCESS,
    LOAD_FEATURED_FAILED
}