

export const MAKE_ORDER_REQUEST="MAKE_ORDER_REQUEST"
export const MAKE_ORDER_SUCCESS="MAKE_ORDER_SUCCESS"
export const MAKE_ORDER_FAILED="MAKE_ORDER_FAILED"


export const LOAD_ORDERS_REQUEST="LOAD_ORDERS_REQUEST"
export const LOAD_ORDERS_SUCCESS="LOAD_ORDERS_SUCCESS"
export const LOAD_ORDERS_FAILED="LOAD_ORDERS_FAILED"

export const LOAD_MORE_ORDERS_REQUEST="LOAD_MORE_ORDERS_REQUEST"
export const LOAD_MORE_ORDERS_SUCCESS="LOAD_MORE_ORDERS_SUCCESS"
export const LOAD_MORE_ORDERS_FAILED="LOAD_MORE_ORDERS_FAILED"

export const CHANGE_ORDERS_STATUS_REQUEST=" CHANGE_ORDERS_STATUS_REQUEST"
export const CHANGE_ORDERS_STATUS_SUCCESS=" CHANGE_ORDERS_STATUS_SUCCESS"
export const CHANGE_ORDERS_STATUS_FAILED=" CHANGE_ORDERS_STATUS_FAILED"