
const LOAD_PRODUCTS_REQUEST="LOAD_PRODUCTS_REQUEST"
const LOAD_PRODUCTS_SUCCESS="LOAD_PRODUCTS_SUCCESS"
const LOAD_PRODUCTS_FAILED="LOAD_PRODUCTS_FAILED"

const LOAD_HOME_PRODUCTS_REQUEST="LOAD_HOME_PRODUCTS_REQUEST"
const LOAD_HOME_PRODUCTS_SUCCESS="LOAD_HOME_PRODUCTS_SUCCESS"
const LOAD_HOME_PRODUCTS_FAILED="LOAD_HOME_PRODUCTS_FAILED"


const SEARCH_PRODUCTS_REQUEST="SEARCH_PRODUCTS_REQUEST"
const SEARCH_PRODUCTS_SUCCESS="SEARCH_PRODUCTS_SUCEESS"
const SEARCH_PRODUCTS_FAILED="SEARCH_PRODUCTS_FAILED"

export


{
    LOAD_HOME_PRODUCTS_REQUEST
    ,

    LOAD_HOME_PRODUCTS_SUCCESS,
    LOAD_HOME_PRODUCTS_FAILED,
    LOAD_PRODUCTS_REQUEST,
    LOAD_PRODUCTS_SUCCESS,
    LOAD_PRODUCTS_FAILED,

    SEARCH_PRODUCTS_FAILED,
    SEARCH_PRODUCTS_REQUEST,
    SEARCH_PRODUCTS_SUCCESS
}