
const LOAD_PRODUCTS_REQUEST="LOAD_PRODUCTS_REQUEST"
const LOAD_PRODUCTS_SUCCESS="LOAD_PRODUCTS_SUCCESS"
const LOAD_PRODUCTS_FAILED="LOAD_PRODUCTS_FAILED"

const LOAD_HOME_PRODUCTS_REQUEST="LOAD_HOME_PRODUCTS_REQUEST"
const LOAD_HOME_PRODUCTS_SUCCESS="LOAD_HOME_PRODUCTS_SUCCESS"
const LOAD_HOME_PRODUCTS_FAILED="LOAD_HOME_PRODUCTS_FAILED"



const LOAD_MORE_PRODUCTS_REQUEST="LOAD_MORE_PRODUCTS_REQUEST"
const LOAD_MORE_PRODUCTS_SUCCESS="LOAD_MORE_PRODUCTS_SUCCESS"
const LOAD_MORE_PRODUCTS_FAILED="LOAD_MORE_PRODUCTS_FAILED"


const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
const DELETE_PRODUCT_FAILED="DELETE_PRODUCT_FAILED"


const ADD_PRODUCT_REQUEST="ADD_PRODUCT_REQUEST"
const ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS"
const ADD_PRODUCT_FAILED="ADD_PRODUCT_FAILED"


export


{
    LOAD_HOME_PRODUCTS_REQUEST,
    LOAD_HOME_PRODUCTS_SUCCESS,
    LOAD_HOME_PRODUCTS_FAILED,


    LOAD_PRODUCTS_REQUEST,
    LOAD_PRODUCTS_SUCCESS,
    LOAD_PRODUCTS_FAILED,

  
    DELETE_PRODUCT_REQUEST,
    DELETE_PRODUCT_SUCCESS,
    DELETE_PRODUCT_FAILED,
    
    LOAD_MORE_PRODUCTS_REQUEST,
    LOAD_MORE_PRODUCTS_SUCCESS,
    LOAD_MORE_PRODUCTS_FAILED,


    ADD_PRODUCT_FAILED,
    ADD_PRODUCT_SUCCESS,
    ADD_PRODUCT_REQUEST,


}