
const LOAD_PRODUCTS_REQUEST="LOAD_PRODUCTS_REQUEST"
const LOAD_PRODUCTS_SUCCESS="LOAD_PRODUCTS_SUCCESS"
const LOAD_PRODUCTS_FAILED="LOAD_PRODUCTS_FAILED"

const LOAD_HOME_PRODUCTS_REQUEST="LOAD_HOME_PRODUCTS_REQUEST"
const LOAD_HOME_PRODUCTS_SUCCESS="LOAD_HOME_PRODUCTS_SUCCESS"
const LOAD_HOME_PRODUCTS_FAILED="LOAD_HOME_PRODUCTS_FAILED"



const LOAD_MORE_PRODUCTS_REQUEST="LOAD_MORE_PRODUCTS_REQUEST"
const LOAD_MORE_PRODUCTS_SUCCESS="LOAD_MORE_PRODUCTS_SUCCESS"
const LOAD_MORE_PRODUCTS_FAILED="LOAD_MORE_PRODUCTS_FAILED"



export


{
    LOAD_HOME_PRODUCTS_REQUEST,
    LOAD_HOME_PRODUCTS_SUCCESS,
    LOAD_HOME_PRODUCTS_FAILED,


    LOAD_PRODUCTS_REQUEST,
    LOAD_PRODUCTS_SUCCESS,
    LOAD_PRODUCTS_FAILED,

  
    LOAD_MORE_PRODUCTS_REQUEST,
    LOAD_MORE_PRODUCTS_SUCCESS,
    LOAD_MORE_PRODUCTS_FAILED
}