




//load products for releted categories
const LOAD_SIMILAR_BY_PRODUCTS_REQUEST="LOAD_SIMILAR_BY_PRODUCTS_REQUEST"
const LOAD_SIMILAR_BY_PRODUCTS_SUCCESS="LOAD_SIMILAR_BY_PRODUCTS_SUCCESS"
const LOAD_SIMILAR_BY_PRODUCTS_FAILED="LOAD_SIMILAR_BY_PRODUCTS_FAILED"

const LOAD_SIMILAR_BY_BRANDS_REQUEST="LOAD_SIMILAR_BY_BRANDS_REQUEST"
const LOAD_SIMILAR_BY_BRANDS_SUCCESS="LOAD_SIMILAR_BY_BRANDS_SUCCESS"
const LOAD_SIMILAR_BY_BRANDS_FAILED="LOAD_SIMILAR_BY_BRANDS_FAILED"


// for lazy loading in similar screen
const LOAD_MORE_SIMILAR_BY_PRODUCTS_REQUEST="LOAD_MORE_SIMILAR_BY_PRODUCTS_REQUEST"
const LOAD_MORE_SIMILAR_BY_PRODUCTS_SUCCESS="LOAD_MORE_SIMILAR_BY_PRODUCTS_SUCCESS"
const LOAD_MORE_SIMILAR_BY_PRODUCTS_FAILED="LOAD_MORE_SIMILAR_BY_PRODUCTS_FAILED"


const LOAD_MORE_SIMILAR_BY_BRANDS_REQUEST="LOAD_MORE_SIMILAR_BY_BRANDS_REQUEST"
const LOAD_MORE_SIMILAR_BY_BRANDS_SUCCESS="LOAD_MORE_SIMILAR_BY_BRANDS_SUCCESS"
const LOAD_MORE_SIMILAR_BY_BRANDS_FAILED="LOAD_MORE_SIMILAR_BY_BRANDS_FAILED"


export  
{
    LOAD_MORE_SIMILAR_BY_BRANDS_REQUEST,
    LOAD_MORE_SIMILAR_BY_BRANDS_SUCCESS,
    LOAD_MORE_SIMILAR_BY_BRANDS_FAILED,
    
    LOAD_SIMILAR_BY_BRANDS_REQUEST,
    LOAD_SIMILAR_BY_BRANDS_SUCCESS,
    LOAD_SIMILAR_BY_BRANDS_FAILED,

    LOAD_SIMILAR_BY_PRODUCTS_REQUEST,
    LOAD_SIMILAR_BY_PRODUCTS_SUCCESS,
    LOAD_SIMILAR_BY_PRODUCTS_FAILED,
    
    LOAD_MORE_SIMILAR_BY_PRODUCTS_REQUEST,
    LOAD_MORE_SIMILAR_BY_PRODUCTS_SUCCESS,
    LOAD_MORE_SIMILAR_BY_PRODUCTS_FAILED,



}