

const ADD_TO_CART="ADD_TO_CART",
const REMOVE_FROM_CART=" REMOVE_FROM_CART"
const LOAD_CART_ITEMS="LOAD_CART_ITEMS"
const CHANGE_QUANTITY="CHANGE_QUANTITY"

export
{
    ADD_TO_CART,REMOVE_FROM_CART,LOAD_CART_ITEMS,CHANGE_QUANTITY
}
